-- -- CREATE TABLE movies(id SERIAL , description VARCHAR(255),name VARCHAR(255),rating INTEGER NOT NULL ,release_date DATE,PRIMARY KEY (id));
-- -- CREATE TABLE userentity(userid SERIAL , username VARCHAR(15) NOT NULL ,password VARCHAR(15) NOT NULL ,PRIMARY KEY (userid));
-- -- CREATE TABLE shows(showid SERIAL , availability INT NOT NULL , city VARCHAR(255),language VARCHAR(255),date DATE,movieid INT, PRIMARY KEY (showid),
-- --   FOREIGN KEY (movieid) REFERENCES movies(id));
-- -- CREATE TABLE shoppingcart(cartid SERIAL , numberoftickets INT, showid INT,userid INT, PRIMARY KEY (cartid),
-- --   FOREIGN KEY (showid) REFERENCES shows(showid),FOREIGN KEY (userid) REFERENCES userentity(userid));
-- --
-- --
--  -- insert into movies(description,name,rating,release_date) values('Classic','Shawshank Redemption','8', '2018-05-10');
-- -- insert into movies(description,name,rating,release_date) values('Action','Avengers','6', '2018-06-10');
-- -- insert into movies(description,name,rating,release_date) values('Fantasy','Harry Potter','7', '2018-05-18');
-- -- insert into movies(description,name,rating,release_date) values('Drama','Titanic','9', '2018-06-12');
-- -- insert into movies(description,name,rating,release_date) values('Fiction','Inception','8', '2018-04-15');
-- --
-- --
-- -- insert into userentity(username,password) values('test','test123');
-- -- insert into userentity(username,password) values('student','student123');
-- -- insert into userentity(username,password) values('admin','admin');
-- --
-- -- insert into shoppingcart(numberoftickets,showid,userid) values(2,1,1);
-- -- insert into shoppingcart(numberoftickets,showid,userid) values(3,2,2);
-- --
-- -- insert into shows(availability,city,language,date,movieid) values(40,'Bangalore','English','2018-06-12',4);
-- -- insert into shows(availability,city,language,date,movieid) values(30,'Delhi','Hindi','2018-04-15',5);
-- -- insert into shows(availability,city,language,date,movieid) values(60,'Chennai','English','2018-06-12',4);
-- -- insert into shows(availability,city,language,date,movieid) values(50,'Mumbai','Hindi','2018-04-15',5);
-- -- insert into shows(availability,city,language,date,movieid) values(20,'Calcutta','English','2018-05-18',3);
-- -- insert into shows(availability,city,language,date,movieid) values(40,'Bangalore','Hindi','2018-05-10',1);
-- -- insert into shows(availability,city,language,date,movieid) values(30,'Delhi','English','2018-05-18',3);
-- -- insert into shows(availability,city,language,date,movieid) values(50,'Chennai','Hindi','2018-06-10',2);
-- -- insert into shows(availability,city,language,date,movieid) values(60,'Mumbai','English','2018-05-10',1);
-- -- insert into shows(availability,city,language,date,movieid) values(20,'Pune','Hindi','2018-06-10',2);